root = "."

[build]
  cmd = "go build -o ./tmp/bot ./cmd/bot"
  bin = "./tmp/bot"
  include_ext = ["go", "sql"]
  exclude_dir = ["tmp", "vendor", "internal/db"]
  delay = 1000

[log]
  time = false

[misc]
  clean_on_exit = true
