global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "web"
    static_configs:
      - targets: ["web:3000"]

  - job_name: "worker"
    static_configs:
      - targets: ["worker:9090"]

  - job_name: "bot"
    static_configs:
      - targets: ["bot:9090"]

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]
